[package]
name = "dom_query"
version = "0.2.0"
description = "HTML manipulation with CSS seletors"
license = "MIT"
repository = "https://github.com/niklak/dom_query"
documentation = "https://docs.rs/dom_query/latest"
keywords = ["html", "css", "selectors", "scraping", "parser"]
authors = ["niklak <morgenpurple@gmail.com>","importcjj <importcjj@gmail.com>"]
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "0.26.0"
selectors = "0.25.0"
cssparser = "0.31.2"
tendril = "0.4.2"
markup5ever = "0.11.0"

indexmap = "2.1.0"
fxhash = "0.2.1"

[dev-dependencies]
reqwest = { version = "0.11.3", features = ["blocking"] }
regex = "1.4.5"
lazy_static = "1.4.0"
readability = "0.3.0"
url = "2.2.1"
