[package]
name = "dom_query"
version = "0.3.2"
description = "HTML manipulation with CSS seletors"
license = "MIT"
repository = "https://github.com/niklak/dom_query"
documentation = "https://docs.rs/dom_query/latest"
keywords = ["html", "css", "selectors", "scraping", "parser"]
authors = ["niklak <morgenpurple@gmail.com>","importcjj <importcjj@gmail.com>"]
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "0.26.0"
selectors = "0.25.0"
cssparser = "0.31.2"
tendril = "0.4.2"
markup5ever = "0.11.0"
rustc-hash = "1.1.0"
hashbrown = {version = "0.14.3", default-features = false, features = ["allocator-api2", "inline-more"], optional = true}

[dev-dependencies]
regex = "1.10.2"
lazy_static = "1.4.0"
readability = {version = "0.3.0", default-features = false}
url = "2.5.0"
ureq = "2.9.1"

[features]
hashbrown = ["dep:hashbrown"]