name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --all
    - name: Run tests
      run: cargo test --verbose --all
    - name: Run tests with hashbrown
      run: cargo test --verbose --all --features "hashbrown"
    - name: Run clippy
      run: cargo clippy --verbose --all -- -D warnings
    - name: Run audit
      run: cargo audit
